const fs = require('fs');
let html = '';
html += '"use client"\n\n';
html += 'import { Calendar, Users, BarChart3, Sparkles, Clock, Shield, TrendingUp, CheckCircle2, Star, ArrowRight, Zap } from "lucide-react"\n\n';
html += 'export default function Home() {\n';
html += '  return (\n';
html += '    <div className="min-h-screen bg-black text-white overflow-hidden">\n';
html += '      <div className="fixed inset-0 bg-gradient-to-br from-indigo-600/20 via-purple-600/20 to-pink-600/20 blur-3xl animate-pulse" style={{animationDuration:"8s"}} />\n';
html += '      <div className="fixed inset-0 bg-gradient-to-r from-indigo-900/20 via-transparent to-transparent animate-pulse" style={{animationDuration:"10s"}} />\n';
html += '      <div className="relative z-10">\n';
html += '        <header className="border-b border-white/10 bg-black/50 backdrop-blur-xl sticky top-0 z-50">\n';
html += '          <div className="container mx-auto px-4 py-4">\n';
html += '            <div className="flex items-center justify-between">\n';
html += '              <div className="flex items-center gap-3">\n';
html += '                <div className="h-10 w-10 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-indigo-500/50">\n';
html += '                  <Calendar className="h-6 w-6 text-white" />\n';
html += '                </div>\n';
html += '                <div>\n';
html += '                  <h1 className="text-2xl font-bold bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">AGENDAKI</h1>\n';
html += '                  <p className="text-xs text-gray-400">Agendamento Inteligente</p>\n';
html += '                </div>\n';
html += '              </div>\n';
html += '              <div className="flex gap-3">\n';
html += '                <button className="px-5 py-2 text-gray-300 hover:text-white transition-colors font-medium">Entrar</button>\n';
html += '                <button className="px-6 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 rounded-xl hover:from-indigo-500 hover:to-purple-500 transition-all shadow-lg shadow-indigo-500/50 font-semibold flex items-center gap-2">Começar Grátis <ArrowRight className="h-4 w-4" /></button>\n';
html += '              </div>\n';
html += '            </div>\n';
html += '          </div>\n';
html += '        </header>\n';
html += '      </div>\n';
html += '    </div>\n';
html += '  )\n';
html += '}\n';
fs.writeFileSync('app/page.tsx', html, 'utf8');
console.log('Done. Size:', html.length);
